name: Build and Deploy frontend

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
# on:
#   push:
#     tags:
#     - '*'

# Environment variables available to all jobs and steps in this workflow
env:
  APP_URL: http://a93ca502557d747d084bc3dfa5bf2c53-2142201707.us-west-2.elb.amazonaws.com/
  IMAGE_PULL_SECRET: spectro-image-pull-secret
  K8S_NAMESPACE: default
#   CLUSTER_NAME: {cluster-name}
#   CLUSTER_RESOURCE_GROUP: {resource-group-name}
#   NAMESPACE: {namespace-name}
#   SECRET: {secret-name}
#   APP_NAME: {app-name}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      git_tag_name: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME }}
    steps:
    - uses: actions/checkout@main
    # - name: Get the version
    #   id: get_tag_name
    #   run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
    - name: Get the version
      id: get_tag_name
      run: echo ::set-output name=GIT_TAG_NAME::${{ github.sha }}
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: _json_key
        password: ${{ secrets.GCLOUD_JSON_KEY }}
        registry: gcr.io
        image_name: spectro-common-dev/saamalik/hipster/frontend
        image_tag: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
  deploy:
    name: Deploy to Dev Env
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
      url: ${{ env.APP_URL }}
    steps:
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}
      id: setcontext
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yaml
        images: |
          gcr.io/spectro-common-dev/saamalik/hipster/frontend:${{ needs.build.outputs.git_tag_name }}
        imagepullsecrets: |
          ${{ env.SECRET }}
        namespace: ${{ env.K8S_NAMESPACE }}
