name: Build and Deploy Dev

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow
env:
  APP_URL: http://ae83e4bb5f8894d29963fac6394e4d2f-551896007.us-west-2.elb.amazonaws.com
  IMAGE_PULL_SECRET: spectro-image-pull-secret
  K8S_NAMESPACE: default
  INTERNAL_HTTPS_PROXY: http://10.10.132.89:3128
  # When using a self-hosted runner, set the http_proxy/https_proxy 
  # inside of the .env file, e.g: https://bit.ly/3qJPmhF

jobs:
  build:
    name: Build
    runs-on: self-hosted #ubuntu-latest
    outputs:
      git_tag_name: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME }}
    steps:
    - uses: actions/checkout@main
    - name: Get the version
      id: get_tag_name
      run: echo ::set-output name=GIT_TAG_NAME::${{ github.sha }}
    - name: Print env
      run: env
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCLOUD_JSON_KEY }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: spectro-common-dev/saamalik/hipster/frontend:${{ steps.get_tag_name.outputs.GIT_TAG_NAME }}
        build-args: |
          https_proxy=${{env.INTERNAL_HTTPS_PROXY}}
          http_proxy=${{env.INTERNAL_HTTPS_PROXY}}
          
    #- uses: whoan/docker-build-with-cache-action@v5
    #  with:
    #    username: _json_key
    #    password: ${{ secrets.GCLOUD_JSON_KEY }}
    #    registry: gcr.io
    #    image_name: spectro-common-dev/saamalik/hipster/frontend
    #    image_tag: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
    #    #build_extra_args: --build-arg=http_proxy=${{ env.http_proxy }} --build-arg=https_proxy=${{ env.https_proxy }}
    #    ## http_proxy/https_proxy should be specified in the runner .env; see comment in the env section above.
  deploy:
    name: Deploy to Dev Env
    runs-on: self-hosted #ubuntu-latest
    needs: build
    environment:
      name: dev
      url: ${{ env.APP_URL }}
    steps:
    - uses: actions/checkout@main
    - uses: spectrocloud/k8s-set-context@v1
      with:
        host: ${{ secrets.SC_HOST }}
        username: ${{ secrets.SC_USERNAME }}
        password: ${{ secrets.SC_PASSWORD }}
        projectName: Default
        clusterTags: |
          cicd: hipster
          dev: spectro__tag
      id: setcontext
    # - name: Print env
    #   run: env
    - uses: azure/k8s-deploy@v1.4
      with:
        manifests: |
          manifests/deployment.yaml
          manifests/service.yaml
        images: |
          gcr.io/spectro-common-dev/saamalik/hipster/frontend:${{ needs.build.outputs.git_tag_name }}
        imagepullsecrets: |
          ${{ env.SECRET }}
        namespace: ${{ env.K8S_NAMESPACE }}
