name: Build and Deploy frontend

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
# on:
#   push:
#     tags:
#     - '*'

# Environment variables available to all jobs and steps in this workflow
env:
  APP_URL: http://ae83e4bb5f8894d29963fac6394e4d2f-551896007.us-west-2.elb.amazonaws.com
  IMAGE_PULL_SECRET: spectro-image-pull-secret
  K8S_NAMESPACE: default
  HTTP_PROXY: http://10.10.132.89:3128
  HTTPS_PROXY: http://10.10.132.89:3128
#   CLUSTER_NAME: {cluster-name}
#   CLUSTER_RESOURCE_GROUP: {resource-group-name}
#   NAMESPACE: {namespace-name}
#   SECRET: {secret-name}
#   APP_NAME: {app-name}

jobs:
  build:
    env:
      HTTP_PROXY: http://10.10.132.89:3128
      HTTPS_PROXY: http://10.10.132.89:3128
    name: Build
    runs-on: self-hosted #ubuntu-latest
    outputs:
      git_tag_name: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME }}
    steps:
    - uses: actions/checkout@main
    - name: Get the version
      id: get_tag_name
      run: echo ::set-output name=GIT_TAG_NAME::${{ github.sha }}
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: _json_key
        password: ${{ secrets.GCLOUD_JSON_KEY }}
        registry: gcr.io
        image_name: spectro-common-dev/saamalik/hipster/frontend
        image_tag: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
        # build_extra_args: --build-arg=http_proxy=${{ env.INTERNAL_HTTPS_PROXY }} --build-arg=HTTP_PROXY=${{ env.INTERNAL_HTTPS_PROXY }}
  deploy:
    name: Deploy to Dev Env
    runs-on: self-hosted #ubuntu-latest
    needs: build
    environment:
      name: dev
      url: ${{ env.APP_URL }}
    steps:
    - uses: actions/checkout@main
    - uses: spectrocloud/k8s-set-context@v1
      with:
        host: ${{ secrets.SC_HOST }}
        username: ${{ secrets.SC_USERNAME }}
        password: ${{ secrets.SC_PASSWORD }}
        projectName: Default
        clusterName: aws-picard-3
      id: setcontext
    - uses: azure/k8s-deploy@v1.4
      with:
        manifests: |
          manifests/deployment.yaml
          manifests/service.yaml
        images: |
          gcr.io/spectro-common-dev/saamalik/hipster/frontend:${{ needs.build.outputs.git_tag_name }}
        imagepullsecrets: |
          ${{ env.SECRET }}
        namespace: ${{ env.K8S_NAMESPACE }}
