on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
# on:
#   push:
#     tags:
#     - '*'

# Environment variables available to all jobs and steps in this workflow
# env:
#   REGISTRY_NAME: {registry-name}
#   CLUSTER_NAME: {cluster-name}
#   CLUSTER_RESOURCE_GROUP: {resource-group-name}
#   NAMESPACE: {namespace-name}
#   SECRET: {secret-name}
#   APP_NAME: {app-name}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    # - name: Get the version
    #   id: get_tag_name
    #   run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
    - name: Get the version
      id: get_tag_name
      run: echo ::set-output name=GIT_TAG_NAME::latest
    - uses: RafikFarhad/push-to-gcr-github-action@v3.0.1
      with:
        gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        registry: gcr.io
        project_id: spectro-common-dev
        image_name: saamalik/hipster/frontend
        image_tag: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
        dockerfile: Dockerfile
